<?php
namespace icelineLtd\icelineLtdDocRenderBundle\Tests\Services\Render;

use icelineLtd\icelineLtdDocRenderBundle\Services\HTMLise;
use icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer;
use icelineLtd\icelineLtdDocRenderBundle\Services\PHPArrayConfig;
use icelineLtd\icelineLtdDocRenderBundle\Tests\Fixture\ChunkMaker;
$_SERVER['SERVER_ADDR']='127.0.0.1';


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-22 at 18:19:51.
 */
class FormRendererTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FormRenderer
     */
    protected $obj;
	protected $maker;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$cfile=__DIR__.'/../../../Resources/config/site_config.php';
		$c=new PHPArrayConfig($cfile);
        $this->obj = new FormRenderer();
		$this->obj->setConfig($c);
		$this->obj->setHTMLise(new HTMLise([], [] ));
		$this->maker=new ChunkMaker();
   }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert $obj->render($in) == 'string'.
     *
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::render
     */
    public function testRender1()
    {
		$in=$this->maker->getForm001();
        $this->assertEquals(
            'string'	,
            gettype($this->obj->render($in))
        );
    }

    public function testRender2()
    {
		$in=$this->maker->getForm002();
        $this->assertEquals(
            'string'	,
            gettype($this->obj->render($in))
        );
    }

/*
    public function testRender3()
    {
		$in=$this->maker->getForm003();
        $this->assertEquals(
            'string'	,
            $this->obj->render($in)
        );
    }



    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::setConfig
     * @todo   Implement testSetConfig().
     */
    public function testSetConfig()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::setSession
     * @todo   Implement testSetSession().
     */
    public function testSetSession()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::setHTMLise
     * @todo   Implement testSetHTMLise().
     */
    public function testSetHTMLise()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::getChunkType
     * @todo   Implement testGetChunkType().
     */
    public function testGetChunkType()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::setFormat
     * @todo   Implement testSetFormat().
     */
    public function testSetFormat()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::generateCSRF
     * @todo   Implement testGenerateCSRF().
     */
    public function testGenerateCSRF()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\FormRenderer::getPreviousPost
     * @todo   Implement testGetPreviousPost().
     */
    public function testGetPreviousPost()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }
}
