<?php
namespace icelineLtd\icelineLtdDocRenderBundle\Tests\Services\Render;

use icelineLtd\icelineLtdDocRenderBundle\Services\HTMLise;
use icelineLtd\icelineLtdDocRenderBundle\Services\Render\TableRenderer;
use icelineLtd\icelineLtdDocRenderBundle\Services\PHPArrayConfig;
use icelineLtd\icelineLtdDocRenderBundle\Tests\Fixture\ChunkMaker;
$_SERVER['SERVER_ADDR']='127.0.0.1';


/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-22 at 20:18:02.
 */
class TableRendererTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TableRenderer
     */
    protected $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$cfile=__DIR__.'/../../../Resources/config/site_config.php';
		$c=new PHPArrayConfig($cfile);
        $this->obj = new TableRenderer();
		$this->obj->setConfig($c);
		$this->obj->setHTMLise(new HTMLise([], [] ));
		$this->maker=new ChunkMaker();
 
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert $obj->render($in) == 'string'.
     *
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\TableRenderer::render
     */
    public function testRender01()
    {
		$in=$this->maker->getTable001();
        $this->assertEquals(
            'string',
            gettype($this->obj->render($in))
        );
    }

    public function testRender02()
    {
		$in=$this->maker->getTable002();
        $this->assertEquals(
            'string',
            gettype($this->obj->render($in))
        );
    }

    public function testRender03()
    {
		$in=$this->maker->getTable003();
        $this->assertEquals(
            'string',
            gettype($this->obj->render($in))
        );
    }



    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\TableRenderer::setConfig
     * @todo   Implement testSetConfig().
     */
    public function testSetConfig()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\TableRenderer::setHTMLise
     * @todo   Implement testSetHTMLise().
     */
    public function testSetHTMLise()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\TableRenderer::setFormat
     * @todo   Implement testSetFormat().
     */
    public function testSetFormat()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Render\TableRenderer::getChunkType
     * @todo   Implement testGetChunkType().
     */
    public function testGetChunkType()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }
}
