<?php
namespace icelineLtd\icelineDocRenderBundle\Tests;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-03 at 15:03:08.
 */ 
abstract class AbstractTidyTest extends \PHPUnit_Framework_TestCase
{
	protected $verbose=true;

   /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		if (! extension_loaded( "tidy" ) || !function_exists('tidy') ) {
			die("This class requires tidy to be available.");
		}

   	}

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

	function isTidy($html) {
		$tidy = new Tidy();
		$tidy->parseString($html, 'utf8');

		if($this->verbose) {
			var_dump($tidy->errorBuffer);
		}
		// maybe extend this to avoid warnings (eg not actual errors)
		return count($tidy->errorBuffer)==0;
	}
}
