<?php
namespace icelineLtd\icelineDocRenderBundle\Tests\Services\Transform;

use icelineLtd\icelineDocRenderBundle\Services\Transform\ExecTransform;
use icelineLtd\icelineDocRenderBundle\Tests\Fixture\ResourceMaker;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-21 at 17:27:42.
 */
class ExecTransformTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ExecTransform
     */
    protected $obj;
	protected $maker;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->obj = new ExecTransform('GET');
		$this->maker=new  ResourceMaker();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert $obj->transform($in) == 'icelineLtd\icelineDocRenderBundle\ResourceInterface'.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\ExecTransform::transform
     */
    public function testTransform1()
    {
		$in=$this->maker->makeFramePage001();
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\ResourceHash',
            get_class($this->obj->transform($in))
        );

		$in=$this->maker->makeFramePage002();
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\ResourceHash',
            get_class($this->obj->transform($in))
        );
    }

    public function testTransform2()
    {
        $this->obj = new ExecTransform('POST');
		$in=$this->maker->makeFramePage001();
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\ResourceHash',
            get_class($this->obj->transform($in))
        );

		$in=$this->maker->makeFramePage002();
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\ResourceHash',
            get_class($this->obj->transform($in))
        );
    }


    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\ExecTransform::setConfig
     * @todo   Implement testSetConfig().
     */
    public function testSetConfig()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\ExecTransform::setLogger
     * @todo   Implement testSetLogger().
     */
    public function testSetLogger()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\ExecTransform::setSession
     * @todo   Implement testSetSession().
     */
    public function testSetSession()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\ExecTransform::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }
}
