<?php
namespace icelineLtd\icelineDocRenderBundle\Tests\Services\Transform;

use icelineLtd\icelineDocRenderBundle\Tests\Mocks\MockPageCollection;
use icelineLtd\icelineDocRenderBundle\Services\Transform\FrameTransform;
use icelineLtd\icelineDocRenderBundle\Tests\Fixture\ResourceMaker;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-20 at 17:37:27.
 */
class FrameTransformTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FrameTransform
     */
    protected $obj;
	protected $maker;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->obj = new FrameTransform();
		$this->obj->setPageCollection(new MockPageCollection() );
		$this->maker=new  ResourceMaker();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert $obj->transform($in) == 'icelineLtd\icelineDocRenderBundle\ResourceInterface'.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\FrameTransform::transform
     */
    public function testTransform001()
    {
		$in=$this->maker->makeFramePage001();
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\ResourceHash',
            get_class($this->obj->transform($in)), 
			"a simple page"
        );
		$in=$this->maker->makeFramePage002();
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\ResourceHash',
            get_class($this->obj->transform($in)), 
			"a good frame holder"
        );
    }

    public function testTransform002() {
		$this->setExpectedException('icelineLtd\icelineDocRenderBundle\Exceptions\BadResourceException');
		$in=$this->maker->makeFramePage003();
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\ResourceInterface',
            get_class($this->obj->transform($in)), 
			"a bad frame holder"
        );
	} 

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\FrameTransform::setPageCollection
     * @todo   Implement testSetPageCollection().
     */
    public function testSetPageCollection()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Transform\FrameTransform::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }
}
