<?php
namespace icelineLtd\icelineDoc\Tests\Services\Transform;

use icelineLtd\icelineDocRenderBundle\Tests\Mocks\MockPageCollection;
use icelineLtd\icelineDocRenderBundle\Services\Transform\TemplateMerge;
use icelineLtd\icelineDocRenderBundle\Tests\Fixture\ResourceMaker;
use icelineLtd\icelineDocRenderBundle\Services\Render\NoTransformRenderer; 
use icelineLtd\icelineDocRenderBundle\Services\StaticValuesFactory;
use icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig ;
$_SERVER['SERVER_ADDR']='127.0.0.1';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-21 at 19:22:01.
 */
class TemplateMergeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TemplateRenderer
     */
    protected $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$cfile=__DIR__.'/../../../Resources/config/site_config.php';
        $this->obj = new TemplateMerge();

		$static=new StaticValuesFactory(new PHPArrayConfig($cfile)) ;
		$static->setPageCollection(new MockPageCollection());
		$this->obj->setStaticsFactory( $static);

		$this->maker=new ResourceMaker();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert $obj->transform($in) == 'the class'.
     *
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Transform\TemplateRenderer::transform
     */
    public function testTransform()
    {
		$in=$this->maker->makeFramePage001();

        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\ResourceHash',
            get_class($this->obj->transform($in))
        );
    }

    /**
     * Generated from @assert $obj->extractMap("tst test [[test001]] test") == "the class".
     *
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Transform\TemplateRenderer::extractMap
     */
    public function testExtractMap()
    {
        $this->assertEquals(
            'icelineLtd\icelineDocRenderBundle\Services\Transform\TemplateMerge',
            get_class($this->obj->extractMap("tst test [[test001]] test"))
        );
    }

    /**
     * Generated from @assert $obj->mapValues(['test001'], $in, $out) == 'array'.
     *
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Transform\TemplateRenderer::mapValues
     */
    public function testMapValues()
    {
		$in=$this->maker->makeFramePage001();
		$out=$this->obj->mapValues(['test01'], $in, $in);
        $this->assertEquals(
            'array',
            gettype($out)
        );
		$this->assertEquals(1, count($out));
    }

    /**
     * Generated from @assert $obj->mapValues(['PANDA STYLE'], $in, $out) == 'array'.
     *
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Transform\TemplateRenderer::mapValues
     */
    public function testMapValues2()
    {
		$in=$this->maker->makeFramePage001();
		$this->setExpectedException('icelineLtd\icelineDocRenderBundle\Exceptions\BadResourceException');
        $this->assertEquals(
            'array',
            gettype($this->obj->mapValues(['PANDA STYLE'], $in, $in))
        );
    }

    /**
     * Generated from @assert $obj->applyMap(['test001'=>"dgdgdfgdf"], $out) == 'array'.
     *
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Transform\TemplateRenderer::applyMap
     */
    public function testApplyMap()
    {
		$in=$this->maker->makeFramePage001();
		$out=$this->obj->applyMap(['test01'=>"dgdgdfgdf"], $in);
        $this->assertEquals(  'integer', gettype($out) );
        $this->assertEquals(  1, $out );
    }


    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Transform\TemplateRenderer::setStaticsFactory
     * @todo   Implement testSetStaticsFactory().
     */
    public function testSetStaticsFactory()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineLtdDocRenderBundle\Services\Transform\TemplateRenderer::render
     * @todo   Implement testRender().
     */
    public function testRender()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }
}
