<?php
namespace icelineLtd\icelineDocRenderBundle\Tests\Services;

use icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig ;
$_SERVER['SERVER_ADDR']='127.0.0.1';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-22 at 17:15:42.
 */
class PHPArrayConfigTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PHPArrayConfig
     */
    protected $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		
		$cfile=__DIR__.'/../../Resources/config/site_config.php';
        $this->obj = new PHPArrayConfig($cfile);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert $obj->get(['site_settings', 'site_language']) == 'en-GB-oed'.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::get
     */
    public function testGet()
    {
        $this->assertEquals(
            'en-GB-oed',
            $this->obj->get(['site_settings', 'site_language'])
        );
    }

    /**
     * Generated from @assert $obj->get(['site_settings', 'PANDA STYLES']) == null.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::get
     */
    public function testGet2()
    {
        $this->assertEquals(
            null,
            $this->obj->get(['site_settings', 'PANDA STYLES'])
        );
    }

    /**
     * Generated from @assert $obj->get('system_resources') == array.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::get
     */
    public function testGet3()
    {
        $this->assertEquals(
            'array',
            gettype($this->obj->get('system_resources'))
        );
    }

    /**
     * Generated from @assert $obj->get(['system_resources', 2]) == '500'.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::get
     */
    public function testGet4()
    {
        $this->assertEquals(
            '500',
            $this->obj->get(['system_resources', 2])
        );
    }

    /**
     * Generated from @assert $obj->get(null) == null.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::get
     */
    public function testGet5()
    {
        $this->assertEquals(
            null,
            $this->obj->get(null)
        );
    }

    /**
     * Generated from @assert $obj->get( ['master_browser_barrier', 'uid', 'type']) == 'int'.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::get
     */
    public function testGet6()
    {
        $this->assertEquals(
            'int',
            $this->obj->get( ['master_browser_barrier', 'uid', 'type'])
        );
    }


    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::load
     * @todo   Implement testLoad().
     */
    public function testLoad()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig::populated
     * @todo   Implement testPopulated().
     */
    public function testPopulated()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }
}
