<?php
namespace icelineLtd\icelineDocRenderBundle\Tests\Services;

use icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig ;
use icelineLtd\icelineDocRenderBundle\Services\WikiFactory ;
use icelineLtd\icelineDocRenderBundle\Tests\Mocks\MockPageCollection;

$_SERVER['SERVER_ADDR']='127.0.0.1';
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-22 at 17:20:43.
 */
class WikiFactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WikiFactory
     */
    protected $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
		$cfile=__DIR__.'/../../Resources/config/site_config.php';
        $this->obj = new WikiFactory();
		$this->obj->setConfig(new PHPArrayConfig($cfile)) ;
		$this->obj->setPageCollection(new MockPageCollection());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * Generated from @assert $obj->get() == 'Text_Wiki'.
     *
     * @covers icelineLtd\icelineDocRenderBundle\Services\WikiFactory::get
     */
    public function testGet()
    {
        $this->assertEquals(
            'Text_Wiki',
            get_class($this->obj->get())
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\WikiFactory::setConfig
     * @todo   Implement testSetConfig().
     */
    public function testSetConfig()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\WikiFactory::setPageCollection
     * @todo   Implement testSetPageCollection().
     */
    public function testSetPageCollection()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }
}
