iceline_ltdiceline_doc_render_homepage:
    path:     /resource/{page}
    defaults: { _controller: @icelineController:renderAction }
    methods: ['GET'] 
    requirements:
       page: ^[a-z0-9-]{3,25}$

