<?php
namespace icelineLtd\icelineDocRenderBundle\Tests\Services\Chunks;

use icelineLtd\icelineDocRenderBundle\Services\Chunks\WikiChunk ;
use icelineLtd\icelineDocRenderBundle\Services\PHPArrayConfig;
$_SERVER['SERVER_ADDR']='127.0.0.1';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-07-04 at 18:03:38.
 */
class WikiChunkTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var WikiChunk
     */
    protected $obj;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->obj = new WikiChunk("name", "value", "type", false);
		$cfile=__DIR__.'/../../../Resources/config/site_config.php';
		$conf=new PHPArrayConfig($cfile);
		$this->obj->setConf($conf);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Chunks\WikiChunk::unpack
     * @todo   Implement testUnpack().
     */
    public function testUnpack()
    {
		$ret=$this->obj->unpack("a1", "++ title\nparagraph text\n", 'wiki', false);
		$this->assertSame(get_class($ret), get_class($this->obj));
// not many varaibles
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Chunks\WikiChunk::validate
     * @todo   Implement testValidate().
     */
    public function testValidate()
    {
		$ret=$this->obj->unpack("a1", "++ title\nparagraph text\n", 'wiki', false);
		$this->assertSame(get_class($ret), get_class($this->obj));	
		$this->assertTrue($ret->validate());	
    }




    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Chunks\WikiChunk::setConf
     * @todo   Implement testSetConf().
     */
    public function testSetConf()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers icelineLtd\icelineDocRenderBundle\Services\Chunks\WikiChunk::getChunkType
     * @todo   Implement testGetChunkType().
     */
    public function testGetChunkType()
    {
        $this->markTestSkipped(
            'This test has not been implemented yet.'
        );
    }

}
